version: '2'
services:
  node:
    container_name: node
    build:
        dockerfile: ./docker/node/Dockerfile
        context: .
    command: ["npm", "run", "watch"]
    volumes:
        - .:/var/www
    ports:
      - "3000:3000"

  db:
    container_name: db
    image: "postgres:11.4"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "tp-node"
