version: 2
jobs:
    build:
        docker:
            - image: circleci/node:12.3
            - image: circleci/postgres:11.4
              environment:
                  POSTGRES_USER: "root"
                  POSTGRES_PASSWORD: "root"
                  POSTGRES_DB: "tp-node"
        working_directory: ~/repo
        steps:
            - checkout
            - run:
                name: installation node module
                command: npm install
            - run:
                name: linter
                command: npm run eslint
            - run:
                name: build
                command: npm run build
            - run:
                name: unit test
                command: npx mocha -r ts-node/register -r tsconfig-paths/register test/**/*.ts --exit
